source = "src"
dest = "docs"
syntaxes = "syntaxes"
syntax_theme = "gruvbox"
custom_syntax_themes = "syntax-themes"

[default]
favicon = "favicon.ico"
stylesheet = "style.css"
template = "template.html"

[generation]
process = { minify = true }
treat_source_as_template = true