name: rustic-raven
version: git
summary: A static html generator
description: |
  Rustic Raven is a static site generator written
  in rust. It's indended to be speedy and easy to
  use.
base: core20
architectures:
  - build-on: [amd64,arm64,i386]
confinement: strict
parts:
  raven:
    plugin: rust
    source: .
apps:
  raven:
    command: bin/raven
grade: devel